export const devList = [
    { i: 'M1', },
    { i: 'M2', },
    { i: 'M3', },
    { i: 'SR', },
    { i: 'A1', },

    { i: 'G1', },
    { i: 'G2' },
    // { i: 'B', x: 11, y: 13, w: 15, h: 9, emptyArea: true, building: true },
    { i: 'HR-G', },

    { i: 'E1', },
    { i: 'E2', },
    { i: 'E3', },
    { i: 'E4', },
    { i: 'E5' },
    { i: 'E6', },
    { i: 'E7', },
    { i: 'E8', },
    { i: 'E9 Sofa', },
    { i: 'E10', },
    { i: 'E11', },
    { i: 'E12' },

    { "devName": "", "i": "s1", "role": "developer", "stack": "frontend", "devId": "a7e6b9f2" },
    { "devName": "", "i": "s2", "role": "developer", "stack": "frontend", "devId": "c9d1e0f8" },
    { "devName": "", "i": "s3", "role": "developer", "stack": "frontend", "devId": "b4c8d5e1" },
    { "devName": "morgan", "i": "s4", "role": "developer", "stack": "php", "devId": "f3a7d2b0" },
    { "devName": "casey", "i": "s5", "role": "developer", "stack": "php", "devId": "d6e8f9a3" },
    { "devName": "", "i": "s6", "role": "developer", "stack": "php", "devId": "e1f9b6c4" },
    { "devName": "jamie", "i": "s7", "role": "developer", "stack": "php", "devId": "a5d3f0e8" },
    { "devName": "dakota", "i": "s8", "role": "developer", "stack": "php", "devId": "c1d8b9a7" },
    { "devName": "avery", "i": "s9", "role": "developer", "stack": "php", "devId": "f0e9c6d2" },
    { "devName": "", "i": "s10", "role": "developer", "stack": "php", "devId": "b3f2a8d1" },
    { "devName": "sydney", "i": "s11", "role": "developer", "stack": "frontend", "devId": "a4c1e9f0" },
    { "devName": "harper", "i": "s12", "role": "developer", "stack": "frontend", "devId": "e9b2f4c5" },
    { "devName": "blake", "i": "s13", "role": "developer", "stack": "frontend", "devId": "c8d3b0f7" },
    { "devName": "", "i": "s14", "role": "developer", "stack": "frontend", "devId": "d5a1e2b8" },
    { "devName": "peyton", "i": "s15", "role": "developer", "stack": "frontend", "devId": "b9d6f3a4" },
    { "devName": "finley", "i": "s16", "role": "developer", "stack": "frontend", "devId": "e2a8c4f6" },
    { "devName": "ariel", "i": "s17", "role": "developer", "stack": "backend", "devId": "f7d2b4a9" },
    { "devName": "lucas", "i": "s18", "role": "developer", "stack": "backend", "devId": "c0e6d3b7" },
    { "devName": "jules", "i": "s19", "role": "developer", "stack": "backend", "devId": "d3b5f7c1" },



    { "devId": "a5d8f7c2", "devName": "", "i": "s20", "role": "developer", "stack": "frontend" },
    { "devId": "b4e9c3a1", "devName": "sandy", "i": "s21", "role": "developer", "stack": "backend" },
    { "devId": "c7d6f8b3", "devName": "vijay", "i": "s22", "role": "developer", "stack": "frontend" },
    { "devId": "d8f3b4e6", "devName": "ajith", "i": "s23", "role": "developer", "stack": "frontend" },
    { "devId": "e1a9d7f3", "devName": "zara", "i": "s24", "role": "developer", "stack": "backend" },
    { "devId": "f6d2c1b8", "devName": "emily", "i": "s25", "role": "developer", "stack": "frontend" },
    { "devId": "g9f7d5e2", "devName": "luca", "i": "s26", "role": "developer", "stack": "frontend" },
    { "devId": "h3d4a7c9", "devName": "zoe", "i": "s27", "role": "developer", "stack": "backend" },
    { "devId": "i8e5f6a1", "devName": "logan", "i": "s28", "role": "developer", "stack": "backend" },
    { "devId": "j7f9b3e5", "devName": "rogers", "i": "s29", "role": "developer", "stack": "frontend" },
    { "devId": "k2d3f6a8", "devName": "maya", "i": "s30", "role": "developer", "stack": "backend" },
    { "devId": "l5b7f2e9", "devName": "", "i": "s31", "role": "developer", "stack": "php" },
    { "devId": "m8c4d6b1", "devName": "jake", "i": "s32", "role": "developer", "stack": "php" },
    { "devId": "n1e3b7a2", "devName": "", "i": "s33", "role": "developer", "stack": "php" },
    { "devId": "o4f2b9e7", "devName": "ella", "i": "s34", "role": "developer", "stack": "backend" },
    { "devId": "p7b3e5c1", "devName": "jack", "i": "s35", "role": "developer", "stack": "php" },
    { "devId": "q2d9a4f8", "devName": "", "i": "s36", "role": "developer", "stack": "php" },
    { "devId": "r8f2b6c3", "devName": "", "i": "s37", "role": "developer", "stack": "backend" },



    { "devName": "jason", "i": "s38", "role": "developer", "stack": "frontend", "devId": "d1234" },
    { "devName": "peter", "i": "s39", "role": "developer", "stack": "frontend", "devId": "d5678" },
    { "devName": "parker", "i": "s40", "role": "developer", "stack": "backend", "devId": "d9101" },
    { "devName": "", "i": "s41", "role": "developer", "stack": "backend", "devId": "d1121" },
    { "devName": "ella", "i": "s42", "role": "developer", "stack": "frontend", "devId": "d3141" },
    { "devName": "", "i": "s43", "role": "developer", "stack": "backend", "devId": "d5161" },
    { "devName": "ryan", "i": "s44", "role": "developer", "stack": "frontend", "devId": "d7181" },
    { "devName": "", "i": "s45", "role": "developer", "stack": "frontend", "devId": "d9202" },
    { "devName": "eva", "i": "s46", "role": "developer", "stack": "backend", "devId": "d1223" },
    { "devName": "ian", "i": "s47", "role": "developer", "stack": "php", "devId": "d3243" },
    { "devName": "mia", "i": "s48", "role": "developer", "stack": "php", "devId": "d5263" },
    { "devName": "leo", "i": "s49", "role": "developer", "stack": "backend", "devId": "d7283" },
    { "devName": "lucas", "i": "s50", "role": "developer", "stack": "php", "devId": "d9303" },
    { "devName": "", "i": "s51", "role": "developer", "stack": "backend", "devId": "d1324" },
    { "devName": "olivia", "i": "s52", "role": "developer", "stack": "php", "devId": "d3344" },
    { "devName": "lily", "i": "s53", "role": "developer", "stack": "php", "devId": "d5364" },
    { "devName": "eva", "i": "s54", "role": "developer", "stack": "backend", "devId": "d7384" },
    { "devName": "tyler", "i": "s55", "role": "developer", "stack": "backend", "devId": "d9404" },
    { "devName": "john", "i": "s56", "role": "developer", "stack": "frontend", "devId": "d1424" },
    { "devName": "Jordan", "i": "s57", "role": "developer", "stack": "frontend", "devId": "d3444" },
    { "devName": "Taylor", "i": "s58", "role": "developer", "stack": "frontend", "devId": "d5464" },
    { "devName": "Morgan", "i": "s59", "role": "developer", "stack": "backend", "devId": "d7484" },
    { "devName": "", "i": "s60", "role": "developer", "stack": "backend", "devId": "d9504" },
    { "devName": "Riley", "i": "s61", "role": "developer", "stack": "frontend", "devId": "d1524" },
    { "devName": "Jamie", "i": "s62", "role": "developer", "stack": "frontend", "devId": "d3544" },
    { "devName": "Dakota", "i": "s63", "role": "developer", "stack": "backend", "devId": "d5564" },
    { "devName": "", "i": "s65", "role": "developer", "stack": "frontend", "devId": "d7584" },
    { "devName": "Quinn", "i": "s66", "role": "developer", "stack": "frontend", "devId": "d9604" },
    { "devName": "Taylor", "i": "s67", "role": "developer", "stack": "frontend", "devId": "d1624" },
    { "devName": "Casey", "i": "s68", "role": "developer", "stack": "backend", "devId": "d3644" },
    { "devName": "Blake", "i": "s70", "role": "developer", "stack": "frontend", "devId": "d5664" },
    { "devName": "Emerson", "i": "s71", "role": "developer", "stack": "backend", "devId": "d7684" },
    { "devName": "Peyton", "i": "s72", "role": "developer", "stack": "frontend", "devId": "d9704" },
    { "devName": "", "i": "s73", "role": "developer", "stack": "backend", "devId": "d1724" },
    { "devName": "Gurunathan", "i": "s74", "role": "developer", "stack": "backend", "devId": "d3744" },


    { "devName": "Marivel", "i": "s75", "role": "developer", "stack": "frontend", "devId": "d1" },
    { "devName": "Venkatesh", "i": "s76", "role": "developer", "stack": "frontend", "devId": "d2" },
    { "devName": "Deepak", "i": "s77", "role": "developer", "stack": "backend", "devId": "d3" },
    { "devName": "Siva sankar", "i": "s78", "role": "developer", "stack": "frontend", "devId": "d4" },
    { "devName": "", "i": "s79", "role": "developer", "stack": "frontend", "devId": "d5" },
    { "devName": "Jamie", "i": "s80", "role": "developer", "stack": "frontend", "devId": "d6" },
    { "devName": "Riley", "i": "s81", "role": "developer", "stack": "backend", "devId": "d7" },
    { "devName": "samule", "i": "s82", "role": "developer", "stack": "backend", "devId": "d7" },
    { "devName": "Avery", "i": "s83", "role": "developer", "stack": "frontend", "devId": "d8" },
    { "devName": "", "i": "s84", "role": "developer", "stack": "frontend", "devId": "d9" },
    { "devName": "Taylor", "i": "s85", "role": "developer", "stack": "frontend", "devId": "d10" },
    { "devName": "Quinn", "i": "s86", "role": "developer", "stack": "backend", "devId": "d11" },
    { "devName": "stark", "i": "s87", "role": "developer", "stack": "backend", "devId": "d11" },
    { "devName": "Blake", "i": "s88", "role": "developer", "stack": "frontend", "devId": "d12" },
    { "devName": "Emerson", "i": "s89", "role": "developer", "stack": "backend", "devId": "d13" },
    { "devName": "", "i": "s90", "role": "developer", "stack": "frontend", "devId": "d14" },
    { "devName": "Alex", "i": "s91", "role": "developer", "stack": "php", "devId": "d15" },
    { "devName": "Alex", "i": "s92", "role": "developer", "stack": "php", "devId": "d16" },
    { "devName": "Jordan", "i": "s93", "role": "developer", "stack": "php", "devId": "d17" },
    { "devName": "", "i": "s94", "role": "developer", "stack": "backend", "devId": "d18" },
    { "devName": "Taylor", "i": "s95", "role": "developer", "stack": "frontend", "devId": "d19" },
    { "devName": "Morgan", "i": "s96", "role": "developer", "stack": "backend", "devId": "d20" },
    { "devName": "perry", "i": "s97", "role": "developer", "stack": "backend", "devId": "d20" },
    { "devName": "", "i": "s98", "role": "developer", "stack": "frontend", "devId": "d21" },
    { "devName": "Quinn", "i": "s99", "role": "developer", "stack": "frontend", "devId": "d22" },
    { "devName": "Dakota", "i": "s100", "role": "developer", "stack": "backend", "devId": "d23" },
    { "devName": "Jamie", "i": "s101", "role": "developer", "stack": "frontend", "devId": "d24" },
    { "devName": "Casey", "i": "s102", "role": "developer", "stack": "frontend", "devId": "d25" },
    { "devName": "Sydney", "i": "s103", "role": "developer", "stack": "backend", "devId": "d26" },
    { "devName": "Jordan", "i": "s104", "role": "developer", "stack": "frontend", "devId": "d27" },
    { "devName": "Casey", "i": "s105", "role": "developer", "stack": "backend", "devId": "d28" },
    { "devName": "Taylor", "i": "s106", "role": "developer", "stack": "backend", "devId": "d29" },
    { "devName": "Morgan", "i": "s107", "role": "developer", "stack": "backend", "devId": "d30" },
    { "devName": "", "i": "s108", "role": "developer", "stack": "frontend", "devId": "d31" },
    { "devName": "Riley", "i": "s109", "role": "developer", "stack": "frontend", "devId": "d32" },
    { "devName": "Quinn", "i": "s110", "role": "developer", "stack": "backend", "devId": "d33" },
    { "devName": "", "i": "s111", "role": "developer", "stack": "backend", "devId": "d34" },
    { "devName": "Alex", "i": "s112", "role": "developer", "stack": "backend", "devId": "d35" },
    { "devName": "Jordan", "i": "s113", "role": "developer", "stack": "frontend", "devId": "d36" },
    { "devName": "Casey", "i": "s114", "role": "developer", "stack": "backend", "devId": "d37" },
    { "devName": "", "i": "s115", "role": "developer", "stack": "backend", "devId": "d38" },

    { "devName": "Alex", "i": "s116", "role": "developer", "stack": "frontend", "devId": "a1b2c3d4" },
    { "devName": "Alex", "i": "s117", "role": "developer", "stack": "backend", "devId": "d5e6f7g8" },
    { "devName": "", "i": "s118", "role": "developer", "stack": "backend", "devId": "h9i0j1k2" },
    { "devName": "Casey", "i": "s119", "role": "developer", "stack": "frontend", "devId": "l3m4n5o6" },
    { "devName": "Taylor", "i": "s120", "role": "developer", "stack": "backend", "devId": "p7q8r9s0" },

    { "devName": "Alex", "i": "s121", "role": "developer", "stack": "frontend", "devId": "t1u2v3w4" },
    { "devName": "Alex", "i": "s122", "role": "developer", "stack": "backend", "devId": "x5y6z7a8" },
    { "devName": "Jordan", "i": "s123", "role": "developer", "stack": "php", "devId": "b9c0d1e2" },
    { "devName": "Casey555", "i": "s124", "role": "developer", "stack": "php", "devId": "f3g4h5i6" },
    { "devName": "", "i": "s125", "role": "developer", "stack": "frontend", "devId": "j7k8l9m0" },

    { "devName": "Taylor 1", "i": "s126", "role": "developer", "stack": "php", "devId": "n1o2p3q4" },
    { "devName": "Taylor 2", "i": "s127", "role": "developer", "stack": "php", "devId": "r5s6t7u8" },
    { "devName": "", "i": "s128", "role": "developer", "stack": "frontend", "devId": "v9w0x1y2" },

    { "devName": "Taylor 3", "i": "s129", "role": "developer", "stack": "backend", "devId": "z3a4b5c6" },
    { "devName": "Taylor 4", "i": "s130", "role": "developer", "stack": "backend", "devId": "d7e8f9g0" },
    { "devName": "Taylor 5", "i": "s131", "role": "developer", "stack": "frontend", "devId": "h1i2j3k4" },
    { "devName": "Taylor 6", "i": "s132", "role": "developer", "stack": "backend", "devId": "l5m6n7o8" },
    { "devName": "Taylor 7", "i": "s133", "role": "developer", "stack": "frontend", "devId": "p9q0r1s2" },

    { "devName": "Taylor 8", "i": "s134", "role": "developer", "stack": "frontend", "devId": "t3u4v5w6" },
    { "devName": "Taylor 9", "i": "s135", "role": "developer", "stack": "backend", "devId": "x7y8z9a0" },
    { "devName": "Taylor 10", "i": "s136", "role": "developer", "stack": "frontend", "devId": "b1c2d3e4" },
    { "devName": "Taylor 11", "i": "s137", "role": "developer", "stack": "frontend", "devId": "f5g6h7i8" },
    { "devName": "", "i": "s138", "role": "developer", "stack": "backend", "devId": "j9k0l1m2" },
    { "devName": "Taylor 12", "i": "s139", "role": "developer", "stack": "php", "devId": "n3o4p5q6" },
    { "devName": "Taylor 13", "i": "s140", "role": "developer", "stack": "frontend", "devId": "r7s8t9u0" },
    { "devName": "Taylor 14", "i": "s141", "role": "developer", "stack": "backend", "devId": "v1w2x3y4" },

    { "devName": "Taylor 15", "i": "s142", "role": "developer", "stack": "php", "devId": "z5a6b7c8" },
    { "devName": "Taylor 16", "i": "s143", "role": "developer", "stack": "frontend", "devId": "d9e0f1g2" }


]
