export const devList = [
    { i: 'M1', },
    { i: 'M2', },
    { i: 'M3', },
    { i: 'SR', },
    { i: 'A1', },
   
    { i: 'G1', },
    { i: 'G2' },
    // { i: 'B', x: 11, y: 13, w: 15, h: 9, emptyArea: true, building: true },
    { i: 'HR-G', },
   
    { i: 'E1', },
    { i: 'E2', },
    { i: 'E3', },
    { i: 'E4', },
    { i: 'E5' },
    { i: 'E6', },
    { i: 'E7', },
    { i: 'E8', },
    { i: 'E9 Sofa', },
    { i: 'E10', },
    { i: 'E11', },
    { i: 'E12' },
   
    { "devName": "", "i": "s1", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "", "i": "s2", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "", "i": "s3", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "morgan", "i": "s4", "role": "developer", "stack": "php", "devId": "f3a7d2b0", "imageUrl": "" },
    { "devName": "casey", "i": "s5", "role": "developer", "stack": "php", "devId": "d6e8f9a3", "imageUrl": "" },
    { "devName": "", "i": "s6", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "jamie", "i": "s7", "role": "developer", "stack": "php", "devId": "a5d3f0e8", "imageUrl": "" },
    { "devName": "dakota", "i": "s8", "role": "developer", "stack": "php", "devId": "c1d8b9a7", "imageUrl": "" },
    { "devName": "avery", "i": "s9", "role": "developer", "stack": "php", "devId": "f0e9c6d2", "imageUrl": "" },
    { "devName": "", "i": "s10", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "sydney", "i": "s11", "role": "developer", "stack": "frontend", "devId": "a4c1e9f0", "imageUrl": "" },
    { "devName": "harper", "i": "s12", "role": "developer", "stack": "frontend", "devId": "e9b2f4c5", "imageUrl": "" },
    { "devName": "blake", "i": "s13", "role": "developer", "stack": "frontend", "devId": "c8d3b0f7", "imageUrl": "" },
    { "devName": "", "i": "s14", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "peyton", "i": "s15", "role": "developer", "stack": "frontend", "devId": "b9d6f3a4", "imageUrl": "" },
    { "devName": "finley", "i": "s16", "role": "developer", "stack": "frontend", "devId": "e2a8c4f6", "imageUrl": "" },
    { "devName": "ariel", "i": "s17", "role": "developer", "stack": "backend", "devId": "f7d2b4a9", "imageUrl": "" },
    { "devName": "lucas", "i": "s18", "role": "developer", "stack": "backend", "devId": "c0e6d3b7", "imageUrl": "" },
    { "devName": "jules", "i": "s19", "role": "developer", "stack": "backend", "devId": "d3b5f7c1", "imageUrl": "" },
   
   
   
    { "devId": "", "devName": "", "i": "s20", "role": "developer", "stack": "", "imageUrl": "" },
    { "devId": "b4e9c3a1", "devName": "sandy", "i": "s21", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "c7d6f8b3", "devName": "vijay", "i": "s22", "role": "developer", "stack": "frontend", "imageUrl": "" },
    { "devId": "d8f3b4e6", "devName": "ajith", "i": "s23", "role": "developer", "stack": "frontend", "imageUrl": "" },
    { "devId": "e1a9d7f3", "devName": "zara", "i": "s24", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "f6d2c1b8", "devName": "emily", "i": "s25", "role": "developer", "stack": "frontend", "imageUrl": "" },
    { "devId": "g9f7d5e2", "devName": "luca", "i": "s26", "role": "developer", "stack": "frontend", "imageUrl": "" },
    { "devId": "h3d4a7c9", "devName": "zoe", "i": "s27", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "i8e5f6a1", "devName": "logan", "i": "s28", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "j7f9b3e5", "devName": "rogers", "i": "s29", "role": "developer", "stack": "frontend", "imageUrl": "" },
    { "devId": "k2d3f6a8", "devName": "maya", "i": "s30", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "", "devName": "", "i": "s31", "role": "developer", "stack": "", "imageUrl": "" },
    { "devId": "m8c4d6b1", "devName": "jake", "i": "s32", "role": "developer", "stack": "php", "imageUrl": "" },
    { "devId": "", "devName": "", "i": "s33", "role": "developer", "stack": "", "imageUrl": "" },
    { "devId": "o4f2b9e7", "devName": "ella", "i": "s34", "role": "developer", "stack": "backend", "imageUrl": "" },
    { "devId": "p7b3e5c1", "devName": "jack", "i": "s35", "role": "developer", "stack": "php", "imageUrl": "" },
    { "devId": "", "devName": "", "i": "s36", "role": "developer", "stack": "", "imageUrl": "" },
    { "devId": "", "devName": "", "i": "s37", "role": "developer", "stack": "", "imageUrl": "" },
   
   
   
    { "devName": "jason", "i": "s38", "role": "developer", "stack": "frontend", "devId": "d1234", "imageUrl": "" },
    { "devName": "peter", "i": "s39", "role": "developer", "stack": "frontend", "devId": "d5678", "imageUrl": "" },
    { "devName": "parker", "i": "s40", "role": "developer", "stack": "backend", "devId": "d9101", "imageUrl": "" },
    { "devName": "", "i": "s41", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "ella", "i": "s42", "role": "developer", "stack": "frontend", "devId": "d3141", "imageUrl": "" },
    { "devName": "", "i": "s43", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "ryan", "i": "s44", "role": "developer", "stack": "frontend", "devId": "d7181", "imageUrl": "" },
    { "devName": "", "i": "s45", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "eva", "i": "s46", "role": "developer", "stack": "backend", "devId": "d1223", "imageUrl": "" },
    { "devName": "ian", "i": "s47", "role": "developer", "stack": "php", "devId": "d3243", "imageUrl": "" },
    { "devName": "mia", "i": "s48", "role": "developer", "stack": "php", "devId": "d5263", "imageUrl": "" },
    { "devName": "leo", "i": "s49", "role": "developer", "stack": "backend", "devId": "d7283", "imageUrl": "" },
    { "devName": "lucas", "i": "s50", "role": "developer", "stack": "php", "devId": "d9303", "imageUrl": "" },
    { "devName": "", "i": "s51", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "olivia", "i": "s52", "role": "developer", "stack": "php", "devId": "d3344", "imageUrl": "" },
    { "devName": "lily", "i": "s53", "role": "developer", "stack": "php", "devId": "d5364", "imageUrl": "" },
    { "devName": "eva", "i": "s54", "role": "developer", "stack": "backend", "devId": "d7384", "imageUrl": "" },
    { "devName": "tyler", "i": "s55", "role": "developer", "stack": "backend", "devId": "d9404", "imageUrl": "" },
    { "devName": "john", "i": "s56", "role": "developer", "stack": "frontend", "devId": "d1424", "imageUrl": "" },
    { "devName": "Jordan", "i": "s57", "role": "developer", "stack": "frontend", "devId": "d3444", "imageUrl": "" },
    { "devName": "Taylor", "i": "s58", "role": "developer", "stack": "frontend", "devId": "d5464", "imageUrl": "" },
    { "devName": "Morgan", "i": "s59", "role": "developer", "stack": "backend", "devId": "d7484", "imageUrl": "" },
    { "devName": "", "i": "s60", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Riley", "i": "s61", "role": "developer", "stack": "frontend", "devId": "d1524", "imageUrl": "" },
    { "devName": "Jamie", "i": "s62", "role": "developer", "stack": "frontend", "devId": "d3544", "imageUrl": "" },
    { "devName": "Dakota", "i": "s63", "role": "developer", "stack": "backend", "devId": "d5564", "imageUrl": "" },
    { "devName": "Test Name", "i": "s64", "role": "developer", "stack": "backend", "devId": "d55641", "imageUrl": "" },
    { "devName": "", "i": "s65", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Quinn", "i": "s66", "role": "developer", "stack": "frontend", "devId": "d9604", "imageUrl": "" },
    { "devName": "Taylor", "i": "s67", "role": "developer", "stack": "frontend", "devId": "d1624", "imageUrl": "" },
    { "devName": "Casey", "i": "s68", "role": "developer", "stack": "backend", "devId": "d3644", "imageUrl": "" },
    { "devName": "Green", "i": "s69", "role": "developer", "stack": "frontend", "devId": "dz647", "imageUrl": "" },
    { "devName": "Blake", "i": "s70", "role": "developer", "stack": "frontend", "devId": "d5664", "imageUrl": "" },
    { "devName": "Emerson", "i": "s71", "role": "developer", "stack": "backend", "devId": "d7684", "imageUrl": "" },
    { "devName": "Peyton", "i": "s72", "role": "developer", "stack": "frontend", "devId": "d9704", "imageUrl": "" },
    { "devName": "", "i": "s73", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Gurunathan", "i": "s74", "role": "developer", "stack": "backend", "devId": "d3744", "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEOT--z-OCSKdMOv-SB4pUsnaCHzFXW7baKHhDpQw4LCe9T7HYuzFQ4tuPgWw9KqxaUIM&usqp=CAU" },
   
   
    { "devName": "Marivel", "i": "s75", "role": "developer", "stack": "frontend", "devId": "d1", "imageUrl": "https://preview.keenthemes.com/metronic-v4/theme_rtl/assets/pages/media/profile/profile_user.jpg" },
    { "devName": "Venkatesh", "i": "s76", "role": "developer", "stack": "frontend", "devId": "d2", "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfkNvSb2Lr58N_6Ih_YjMcTTzqSxgAkwHEKPkP41P3IN0u6J7-3P-y4UnLAHEQbXUWfFk&usqp=CAU" },
    { "devName": "Deepak", "i": "s77", "role": "developer", "stack": "backend", "devId": "d3", "imageUrl": "https://png.pngtree.com/png-vector/20221203/ourmid/pngtree-cartoon-style-female-user-profile-icon-vector-illustraton-png-image_6489286.png" },
    { "devName": "Siva sankar", "i": "s78", "role": "developer", "stack": "frontend", "devId": "d4", "imageUrl": "https://i.imgur.com/JFHjdNr.jpg" },
    { "devName": "", "i": "s79", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Jamie", "i": "s80", "role": "developer", "stack": "frontend", "devId": "d6", "imageUrl": "" },
    { "devName": "Riley", "i": "s81", "role": "developer", "stack": "backend", "devId": "d71", "imageUrl": "" },
    { "devName": "samule", "i": "s82", "role": "developer", "stack": "backend", "devId": "d72", "imageUrl": "" },
    { "devName": "Avery", "i": "s83", "role": "developer", "stack": "frontend", "devId": "d8", "imageUrl": "" },
    { "devName": "", "i": "s84", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Taylor", "i": "s85", "role": "developer", "stack": "frontend", "devId": "d10", "imageUrl": "" },
    { "devName": "Quinn", "i": "s86", "role": "developer", "stack": "backend", "devId": "d111", "imageUrl": "" },
    { "devName": "stark", "i": "s87", "role": "developer", "stack": "backend", "devId": "d112", "imageUrl": "" },
    { "devName": "Blake", "i": "s88", "role": "developer", "stack": "frontend", "devId": "d12", "imageUrl": "" },
    { "devName": "Emerson", "i": "s89", "role": "developer", "stack": "backend", "devId": "d13", "imageUrl": "" },
    { "devName": "", "i": "s90", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Alex", "i": "s91", "role": "developer", "stack": "php", "devId": "d15", "imageUrl": "" },
    { "devName": "Alex", "i": "s92", "role": "developer", "stack": "php", "devId": "d16", "imageUrl": "" },
    { "devName": "Jordan", "i": "s93", "role": "developer", "stack": "php", "devId": "d17", "imageUrl": "" },
    { "devName": "", "i": "s94", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Taylor", "i": "s95", "role": "developer", "stack": "frontend", "devId": "d19", "imageUrl": "" },
    { "devName": "Morgan", "i": "s96", "role": "developer", "stack": "backend", "devId": "d201", "imageUrl": "" },
    { "devName": "perry", "i": "s97", "role": "developer", "stack": "backend", "devId": "d202", "imageUrl": "" },
    { "devName": "", "i": "s98", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Quinn", "i": "s99", "role": "developer", "stack": "frontend", "devId": "d22", "imageUrl": "" },
    { "devName": "Dakota", "i": "s100", "role": "developer", "stack": "backend", "devId": "d23", "imageUrl": "" },
    { "devName": "Jamie", "i": "s101", "role": "developer", "stack": "frontend", "devId": "d24", "imageUrl": "" },
    { "devName": "Casey", "i": "s102", "role": "developer", "stack": "frontend", "devId": "d25", "imageUrl": "" },
    { "devName": "Sydney", "i": "s103", "role": "developer", "stack": "backend", "devId": "d26", "imageUrl": "" },
    { "devName": "Jordan", "i": "s104", "role": "developer", "stack": "frontend", "devId": "d27", "imageUrl": "" },
    { "devName": "Casey", "i": "s105", "role": "developer", "stack": "backend", "devId": "d28", "imageUrl": "" },
    { "devName": "Taylor", "i": "s106", "role": "developer", "stack": "backend", "devId": "d29", "imageUrl": "" },
    { "devName": "Morgan", "i": "s107", "role": "developer", "stack": "backend", "devId": "d30", "imageUrl": "" },
    { "devName": "", "i": "s108", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Riley", "i": "s109", "role": "developer", "stack": "frontend", "devId": "d32", "imageUrl": "" },
    { "devName": "Quinn", "i": "s110", "role": "developer", "stack": "backend", "devId": "d33", "imageUrl": "" },
    { "devName": "", "i": "s111", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Alex", "i": "s112", "role": "developer", "stack": "backend", "devId": "d35", "imageUrl": "" },
    { "devName": "Jordan", "i": "s113", "role": "developer", "stack": "frontend", "devId": "d36", "imageUrl": "" },
    { "devName": "Casey", "i": "s114", "role": "developer", "stack": "backend", "devId": "d37", "imageUrl": "" },
    { "devName": "", "i": "s115", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
   
    { "devName": "Alex", "i": "s116", "role": "developer", "stack": "frontend", "devId": "a1b2c3d4", "imageUrl": "" },
    { "devName": "Alex", "i": "s117", "role": "developer", "stack": "backend", "devId": "d5e6f7g8", "imageUrl": "" },
    { "devName": "", "i": "s118", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Casey", "i": "s119", "role": "developer", "stack": "frontend", "devId": "l3m4n5o6", "imageUrl": "" },
    { "devName": "Taylor", "i": "s120", "role": "developer", "stack": "backend", "devId": "p7q8r9s0", "imageUrl": "" },
   
    { "devName": "Alex", "i": "s121", "role": "developer", "stack": "frontend", "devId": "t1u2v3w4", "imageUrl": "" },
    { "devName": "Alex", "i": "s122", "role": "developer", "stack": "backend", "devId": "x5y6z7a8", "imageUrl": "" },
    { "devName": "Jordan", "i": "s123", "role": "developer", "stack": "php", "devId": "b9c0d1e2", "imageUrl": "" },
    { "devName": "Casey555", "i": "s124", "role": "developer", "stack": "php", "devId": "f3g4h5i6", "imageUrl": "" },
    { "devName": "", "i": "s125", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
   
    { "devName": "Taylor 1", "i": "s126", "role": "developer", "stack": "php", "devId": "n1o2p3q4", "imageUrl": "" },
    { "devName": "Taylor 2", "i": "s127", "role": "developer", "stack": "php", "devId": "r5s6t7u8", "imageUrl": "" },
    { "devName": "", "i": "s128", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
   
    { "devName": "Taylor 3", "i": "s129", "role": "developer", "stack": "backend", "devId": "z3a4b5c6", "imageUrl": "" },
    { "devName": "Taylor 4", "i": "s130", "role": "developer", "stack": "backend", "devId": "d7e8f9g0", "imageUrl": "" },
    { "devName": "Taylor 5", "i": "s131", "role": "developer", "stack": "frontend", "devId": "h1i2j3k4", "imageUrl": "" },
    { "devName": "Taylor 6", "i": "s132", "role": "developer", "stack": "backend", "devId": "l5m6n7o8", "imageUrl": "" },
    { "devName": "Taylor 7", "i": "s133", "role": "developer", "stack": "frontend", "devId": "p9q0r1s2", "imageUrl": "" },
   
    { "devName": "Taylor 8", "i": "s134", "role": "developer", "stack": "frontend", "devId": "t3u4v5w6", "imageUrl": "" },
    { "devName": "Taylor 9", "i": "s135", "role": "developer", "stack": "backend", "devId": "x7y8z9a0", "imageUrl": "" },
    { "devName": "Taylor 10", "i": "s136", "role": "developer", "stack": "frontend", "devId": "b1c2d3e4", "imageUrl": "" },
    { "devName": "Taylor 11", "i": "s137", "role": "developer", "stack": "frontend", "devId": "f5g6h7i8", "imageUrl": "" },
    { "devName": "", "i": "s138", "role": "developer", "stack": "", "devId": "", "imageUrl": "" },
    { "devName": "Taylor 12", "i": "s139", "role": "developer", "stack": "php", "devId": "n3o4p5q6", "imageUrl": "" },
    { "devName": "Taylor 13", "i": "s140", "role": "developer", "stack": "frontend", "devId": "r7s8t9u0", "imageUrl": "" },
    { "devName": "Taylor 14", "i": "s141", "role": "developer", "stack": "backend", "devId": "v1w2x3y4", "imageUrl": "" },
   
    { "devName": "Taylor 15", "i": "s142", "role": "developer", "stack": "php", "devId": "z5a6b7c8", "imageUrl": "" },
    { "devName": "Taylor 16", "i": "s143", "role": "developer", "stack": "frontend", "devId": "d9e0f1g2", "imageUrl": "" }
   
   
   ]