export const devList = [

    { "devName": "Akash", "seat_id": "s1", "role": "developer", "stack": "frontend", "devId": "a7e6b9f2", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "Ranjith", "seat_id": "s2", "role": "developer", "stack": "frontend", "devId": "c9d1e0f8", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "Rajavel", "seat_id": "s3", "role": "developer", "stack": "frontend", "devId": "b4c8d5e1", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "morgan", "seat_id": "s4", "role": "developer", "stack": "php", "devId": "f3a7d2b0", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "casey", "seat_id": "s5", "role": "developer", "stack": "php", "devId": "d6e8f9a3", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "Rajesh", "seat_id": "s6", "role": "developer", "stack": "php", "devId": "e1f9b6c4", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "jamie", "seat_id": "s7", "role": "developer", "stack": "php", "devId": "a5d3f0e8", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "dakota", "seat_id": "s8", "role": "developer", "stack": "php", "devId": "c1d8b9a7", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "avery", "seat_id": "s9", "role": "developer", "stack": "php", "devId": "f0e9c6d2", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "Siva", "seat_id": "s10", "role": "developer", "stack": "php", "devId": "b3f2a8d1", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "sydney", "seat_id": "s11", "role": "developer", "stack": "frontend", "devId": "a4c1e9f0", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "harper", "seat_id": "s12", "role": "developer", "stack": "frontend", "devId": "e9b2f4c5", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "blake", "seat_id": "s13", "role": "developer", "stack": "frontend", "devId": "c8d3b0f7", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "Subash", "seat_id": "s14", "role": "developer", "stack": "frontend", "devId": "d5a1e2b8", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "peyton", "seat_id": "s15", "role": "developer", "stack": "frontend", "devId": "b9d6f3a4", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "finley", "seat_id": "s16", "role": "developer", "stack": "frontend", "devId": "e2a8c4f6", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "ariel", "seat_id": "s17", "role": "developer", "stack": "backend", "devId": "f7d2b4a9", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "lucas", "seat_id": "s18", "role": "developer", "stack": "backend", "devId": "c0e6d3b7", "isFresher": false, "TL_id": "a7e6b9f2" },
    { "devName": "jules", "seat_id": "s19", "role": "developer", "stack": "backend", "devId": "d3b5f7c1", "isFresher": false, "TL_id": "a7e6b9f2" },



    { "devId": "a5d8f7c2", "devName": "Yajirobe", "seat_id": "s20", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "b4e9c3a1", "devName": "sandy", "seat_id": "s21", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "c7d6f8b3", "devName": "vijay", "seat_id": "s22", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "d8f3b4e6", "devName": "ajith", "seat_id": "s23", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "e1a9d7f3", "devName": "zara", "seat_id": "s24", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "f6d2c1b8", "devName": "emily", "seat_id": "s25", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "g9f7d5e2", "devName": "luca", "seat_id": "s26", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "h3d4a7c9", "devName": "zoe", "seat_id": "s27", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "i8e5f6a1", "devName": "logan", "seat_id": "s28", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "j7f9b3e5", "devName": "rogers", "seat_id": "s29", "role": "developer", "stack": "frontend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "k2d3f6a8", "devName": "maya", "seat_id": "s30", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "l5b7f2e9", "devName": "Goku", "seat_id": "s31", "role": "developer", "stack": "php", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "m8c4d6b1", "devName": "jake", "seat_id": "s32", "role": "developer", "stack": "php", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "n1e3b7a2", "devName": "Kuririn", "seat_id": "s33", "role": "developer", "stack": "php", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "o4f2b9e7", "devName": "ella", "seat_id": "s34", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "p7b3e5c1", "devName": "jack", "seat_id": "s35", "role": "developer", "stack": "php", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "q2d9a4f8", "devName": "Muten Roshi", "seat_id": "s36", "role": "developer", "stack": "php", "isFresher": false, "TL_id": "a5d8f7c2" },
    { "devId": "r8f2b6c3", "devName": "Zamasu", "seat_id": "s37", "role": "developer", "stack": "backend", "isFresher": false, "TL_id": "a5d8f7c2" },



    { "devName": "jason", "seat_id": "s38", "role": "developer", "stack": "frontend", "devId": "d1234", "isFresher": false, "TL_id": "d1234" },
    { "devName": "peter", "seat_id": "s39", "role": "developer", "stack": "frontend", "devId": "d5678", "isFresher": false, "TL_id": "d1234" },
    { "devName": "parker", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d9101", "isFresher": false, "TL_id": "d1234" },
    { "devName": "Gawasu", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d1121", "isFresher": false, "TL_id": "d1234" },
    { "devName": "ella", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d3141", "isFresher": false, "TL_id": "d1234" },
    { "devName": "KaioShin", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d5161", "isFresher": false, "TL_id": "d1234" },
    { "devName": "ryan", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d7181", "isFresher": false, "TL_id": "d1234" },
    { "devName": "Beerus", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9202", "isFresher": false, "TL_id": "d1234" },
    { "devName": "eva", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d1223", "isFresher": false, "TL_id": "d1234" },
    { "devName": "ian", "seat_id": "", "role": "developer", "stack": "php", "devId": "d3243", "isFresher": false, "TL_id": "d1234" },
    { "devName": "mia", "seat_id": "", "role": "developer", "stack": "php", "devId": "d5263", "isFresher": false, "TL_id": "d1234" },
    { "devName": "leo", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d7283", "isFresher": false, "TL_id": "d1234" },
    { "devName": "lucas", "seat_id": "", "role": "developer", "stack": "php", "devId": "d9303", "isFresher": false, "TL_id": "d1234" },
    { "devName": "Whis", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d1324", "isFresher": false, "TL_id": "d1234" },
    { "devName": "olivia", "seat_id": "", "role": "developer", "stack": "php", "devId": "d3344", "isFresher": false, "TL_id": "d1234" },
    { "devName": "lily", "seat_id": "", "role": "developer", "stack": "php", "devId": "d5364", "isFresher": false, "TL_id": "d1234" },
    { "devName": "eva", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d7384", "isFresher": false, "TL_id": "d1234" },
    { "devName": "tyler", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d9404", "isFresher": false, "TL_id": "d1234" },
    { "devName": "john", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d1424", "isFresher": false, "TL_id": "d1234" },
    { "devName": "Jordan", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d3444", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Taylor", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d5464", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Morgan", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d7484", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Vegeta", "seat_id": "", "role": "developer", "stack": "backend", "devId": "d9504", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Riley", "seat_id": "s61", "role": "developer", "stack": "frontend", "devId": "d1524", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Jamie", "seat_id": "s62", "role": "developer", "stack": "frontend", "devId": "d3544", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Dakota", "seat_id": "s63", "role": "developer", "stack": "backend", "devId": "d5564", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Teinshinhan", "seat_id": "s65", "role": "developer", "stack": "frontend", "devId": "d7584", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Quinn", "seat_id": "s66", "role": "developer", "stack": "frontend", "devId": "d9604", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Taylor", "seat_id": "s67", "role": "developer", "stack": "frontend", "devId": "d1624", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Casey", "seat_id": "s68", "role": "developer", "stack": "backend", "devId": "d3644", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Blake", "seat_id": "s70", "role": "developer", "stack": "frontend", "devId": "d5664", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Emerson", "seat_id": "s71", "role": "developer", "stack": "backend", "devId": "d7684", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Peyton", "seat_id": "s72", "role": "developer", "stack": "frontend", "devId": "d9704", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Trunks", "seat_id": "s73", "role": "developer", "stack": "backend", "devId": "d1724", "isFresher": false, "TL_id": "d3444" },
    { "devName": "Gurunathan", "seat_id": "s74", "role": "developer", "stack": "backend", "devId": "d3744", "isFresher": false, "TL_id": "d3444" },


    { "devName": "Marivel", "seat_id": "s75", "role": "developer", "stack": "frontend", "devId": "d1", "isFresher": false, "TL_id": "d1" },
    { "devName": "Venkatesh", "seat_id": "s76", "role": "developer", "stack": "frontend", "devId": "d2", "isFresher": false, "TL_id": "d1" },
    { "devName": "Deepak", "seat_id": "s77", "role": "developer", "stack": "backend", "devId": "d3", "isFresher": false, "TL_id": "d1" },
    { "devName": "Siva sankar", "seat_id": "s78", "role": "developer", "stack": "frontend", "devId": "d4", "isFresher": false, "TL_id": "d1" },
    { "devName": "Gohan", "seat_id": "s79", "role": "developer", "stack": "frontend", "devId": "d5", "isFresher": false, "TL_id": "d1" },
    { "devName": "Jamie", "seat_id": "s80", "role": "developer", "stack": "frontend", "devId": "d6", "isFresher": false, "TL_id": "d1" },
    { "devName": "Riley", "seat_id": "s81", "role": "developer", "stack": "backend", "devId": "d71", "isFresher": false, "TL_id": "d1" },
    { "devName": "samule", "seat_id": "s82", "role": "developer", "stack": "backend", "devId": "d7", "isFresher": false, "TL_id": "d1" },
    { "devName": "Avery", "seat_id": "s83", "role": "developer", "stack": "frontend", "devId": "d8", "isFresher": false, "TL_id": "d1" },
    { "devName": "Goten", "seat_id": "s84", "role": "developer", "stack": "frontend", "devId": "d9", "isFresher": false, "TL_id": "d1" },
    { "devName": "Taylor", "seat_id": "s85", "role": "developer", "stack": "frontend", "devId": "d10", "isFresher": false, "TL_id": "d1" },
    { "devName": "Quinn", "seat_id": "s86", "role": "developer", "stack": "backend", "devId": "d11", "isFresher": false, "TL_id": "d1" },
    { "devName": "stark", "seat_id": "s87", "role": "developer", "stack": "backend", "devId": "d11", "isFresher": false, "TL_id": "d1" },
    { "devName": "Blake", "seat_id": "s88", "role": "developer", "stack": "frontend", "devId": "d12", "isFresher": false, "TL_id": "d1" },
    { "devName": "Emerson", "seat_id": "s89", "role": "developer", "stack": "backend", "devId": "d13", "isFresher": false, "TL_id": "d1" },
    { "devName": "Mai", "seat_id": "s90", "role": "developer", "stack": "frontend", "devId": "d14", "isFresher": false, "TL_id": "d1" },
    { "devName": "Alex", "seat_id": "s91", "role": "developer", "stack": "php", "devId": "d15", "isFresher": false, "TL_id": "d1" },
    { "devName": "Alex", "seat_id": "s92", "role": "developer", "stack": "php", "devId": "d16", "isFresher": false, "TL_id": "d1" },
    { "devName": "Jordan", "seat_id": "s93", "role": "developer", "stack": "php", "devId": "d17", "isFresher": false, "TL_id": "d1" },
    { "devName": "Bulma", "seat_id": "s94", "role": "developer", "stack": "backend", "devId": "d18", "isFresher": false, "TL_id": "d1" },
    { "devName": "Taylor", "seat_id": "s95", "role": "developer", "stack": "frontend", "devId": "d19", "isFresher": false, "TL_id": "d1" },
    { "devName": "Morgan", "seat_id": "s96", "role": "developer", "stack": "backend", "devId": "d201", "isFresher": false, "TL_id": "d20" },
    { "devName": "perry", "seat_id": "s97", "role": "developer", "stack": "backend", "devId": "d20", "isFresher": false, "TL_id": "d20" },
    { "devName": "Chichi", "seat_id": "s98", "role": "developer", "stack": "frontend", "devId": "d21", "isFresher": false, "TL_id": "d20" },
    { "devName": "Quinn", "seat_id": "s99", "role": "developer", "stack": "frontend", "devId": "d22", "isFresher": false, "TL_id": "d20" },
    { "devName": "Dakota", "seat_id": "s100", "role": "developer", "stack": "backend", "devId": "d23", "isFresher": false, "TL_id": "d20" },
    { "devName": "Jamie", "seat_id": "s101", "role": "developer", "stack": "frontend", "devId": "d24", "isFresher": false, "TL_id": "d20" },
    { "devName": "Casey", "seat_id": "s102", "role": "developer", "stack": "frontend", "devId": "d25", "isFresher": false, "TL_id": "d20" },
    // { "devName": "Sydney", "seat_id": "s103", "role": "developer", "stack": "backend", "devId": "d26", "isFresher": false, "TL_id": "d20" },
    { "devName": "Jordan", "seat_id": "s104", "role": "developer", "stack": "frontend", "devId": "d27", "isFresher": false, "TL_id": "d20" },
    { "devName": "Casey", "seat_id": "s105", "role": "developer", "stack": "backend", "devId": "d28", "isFresher": false, "TL_id": "d20" },
    { "devName": "Taylor", "seat_id": "s106", "role": "developer", "stack": "backend", "devId": "d29", "isFresher": false, "TL_id": "d20" },
    { "devName": "Morgan", "seat_id": "s107", "role": "developer", "stack": "backend", "devId": "d30", "isFresher": false, "TL_id": "d20" },
    { "devName": "Kaio", "seat_id": "s108", "role": "developer", "stack": "frontend", "devId": "d31", "isFresher": false, "TL_id": "d20" },
    { "devName": "Riley", "seat_id": "s109", "role": "developer", "stack": "frontend", "devId": "d32", "isFresher": false, "TL_id": "d20" },
    { "devName": "Quinn", "seat_id": "s110", "role": "developer", "stack": "backend", "devId": "d33", "isFresher": false, "TL_id": "d20" },
    { "devName": "Shin", "seat_id": "s111", "role": "developer", "stack": "backend", "devId": "d34", "isFresher": false, "TL_id": "d20" },
    { "devName": "Alex", "seat_id": "s112", "role": "developer", "stack": "backend", "devId": "d35", "isFresher": false, "TL_id": "d20" },
    { "devName": "Jordan", "seat_id": "s113", "role": "developer", "stack": "frontend", "devId": "d36", "isFresher": false, "TL_id": "d20" },
    { "devName": "Casey", "seat_id": "s114", "role": "developer", "stack": "backend", "devId": "d37", "isFresher": false, "TL_id": "d20" },
    { "devName": "Monaka", "seat_id": "s115", "role": "developer", "stack": "backend", "devId": "d38", "isFresher": false, "TL_id": "d20" },

    { "devName": "Santhosh", "seat_id": "s116", "role": "developer", "stack": "frontend", "devId": "a1b2c3d4", "isFresher": false, "TL_id": "a1b2c3d4" },
    { "devName": "Alexis", "seat_id": "s117", "role": "developer", "stack": "backend", "devId": "d5e6f7g8", "isFresher": false, "TL_id": "a1b2c3d4" },
    { "devName": "Cell", "seat_id": "s118", "role": "developer", "stack": "backend", "devId": "h9i0j1k2", "isFresher": false, "TL_id": "a1b2c3d4" },
    { "devName": "Casey", "seat_id": "s119", "role": "developer", "stack": "frontend", "devId": "l3m4n5o6", "isFresher": false, "TL_id": "a1b2c3d4" },
    { "devName": "Taylor", "seat_id": "s120", "role": "developer", "stack": "backend", "devId": "p7q8r9s0", "isFresher": false, "TL_id": "a1b2c3d4" },

    { "devName": "Alex", "seat_id": "s121", "role": "developer", "stack": "frontend", "devId": "t1u2v3w4", "isFresher": false, "TL_id": "t1u2v3w4" },
    { "devName": "AlexFelix", "seat_id": "s122", "role": "developer", "stack": "backend", "devId": "x5y6z7a8", "isFresher": false, "TL_id": "t1u2v3w4" },
    { "devName": "Jordan", "seat_id": "s123", "role": "developer", "stack": "php", "devId": "b9c0d1e2", "isFresher": false, "TL_id": "t1u2v3w4" },
    { "devName": "Casey555", "seat_id": "s124", "role": "developer", "stack": "php", "devId": "f3g4h5i6", "isFresher": false, "TL_id": "t1u2v3w4" },
    { "devName": "Pan", "seat_id": "s125", "role": "developer", "stack": "frontend", "devId": "j7k8l9m0", "isFresher": false, "TL_id": "t1u2v3w4" },

    { "devName": "Taylor 1", "seat_id": "s126", "role": "developer", "stack": "php", "devId": "n1o2p3q4", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 2", "seat_id": "s127", "role": "developer", "stack": "php", "devId": "r5s6t7u8", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Videl", "seat_id": "s128", "role": "developer", "stack": "frontend", "devId": "v9w0x1y2", "isFresher": false, "TL_id": "n1o2p3q4" },

    { "devName": "Taylor 3", "seat_id": "s129", "role": "developer", "stack": "backend", "devId": "z3a4b5c6", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 4", "seat_id": "s130", "role": "developer", "stack": "backend", "devId": "d7e8f9g0", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 5", "seat_id": "s131", "role": "developer", "stack": "frontend", "devId": "h1i2j3k4", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 6", "seat_id": "s132", "role": "developer", "stack": "backend", "devId": "l5m6n7o8", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 7", "seat_id": "s133", "role": "developer", "stack": "frontend", "devId": "p9q0r1s2", "isFresher": false, "TL_id": "n1o2p3q4" },

    { "devName": "Taylor 8", "seat_id": "s134", "role": "developer", "stack": "frontend", "devId": "t3u4v5w6", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 9", "seat_id": "s135", "role": "developer", "stack": "backend", "devId": "x7y8z9a0", "isFresher": false, "TL_id": "n1o2p3q4" },
    { "devName": "Taylor 10", "seat_id": "s136", "role": "developer", "stack": "frontend", "devId": "b1c2d3e4", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 11", "seat_id": "s137", "role": "developer", "stack": "frontend", "devId": "f5g6h7i8", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Satan", "seat_id": "s138", "role": "developer", "stack": "backend", "devId": "j9k0l1m2", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 12", "seat_id": "s139", "role": "developer", "stack": "php", "devId": "n3o4p5q6", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 13", "seat_id": "s140", "role": "developer", "stack": "frontend", "devId": "r7s8t9u0", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 14", "seat_id": "s141", "role": "developer", "stack": "backend", "devId": "v1w2x3y4", "isFresher": false, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 15", "seat_id": "s142", "role": "developer", "stack": "php", "devId": "z5a6b7c8", "isFresher": false, "TL_id": "f5g6h7i8" },

    { "devName": "Taylor 16", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9e0f1g2", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 17", "seat_id": "", "role": "developer", "stack": "php", "devId": "z5a6b7c9", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 18", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9e0f1g3", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 19", "seat_id": "", "role": "developer", "stack": "php", "devId": "z5a6b7c10", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 20", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9e0f1g4", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 21", "seat_id": "", "role": "developer", "stack": "php", "devId": "z5a6b7c11", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 22", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9e0f1g5", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 23", "seat_id": "", "role": "developer", "stack": "php", "devId": "z5a6b7c12", "isFresher": true, "TL_id": "f5g6h7i8" },
    { "devName": "Taylor 24", "seat_id": "", "role": "developer", "stack": "frontend", "devId": "d9e0f1g6", "isFresher": true, "TL_id": "f5g6h7i8" },

]