export const layouts = {
    layout1: [
    { i: 'M1', x: 0, y: 0, w: 3, h: 2.5, unchange: true ,extension_no : -1 },
    { i: 'M2', x: 22, y: 0, w: 3, h: 2.5, unchange: true,extension_no : -1 },
    { i: 'M3', x: 22, y: 6, w: 3, h: 2.5, unchange: true,extension_no : -1 },
    { i: 'SR', x: 3, y: 0, w: 1, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'A1', x: 0, y: 2, w: 3, h: 3.5, unchange: true,extension_no : -1 },
   
    { i: 'G1', x: 10, y: 13, w: 1, h: 11, emptyArea: true, gate: true, unchange: true },
    { i: 'G2', x: 0, y: 18, w: 0.5, h: 2, emptyArea: true, unchange: true },
    { i: 'Box', x: 0, y: 17, w: 0.5, h: 2, emptyArea: true, unchange: true ,extension_no : -1 },
    { i: 'Empty Area', x: 11, y: 13, w: 14, h: 18, emptyArea: true ,unchange: true},
    { i: 'HR-G', x: 22, y: 3, w: 3, h: 4, emptyArea: true, unchange: true,extension_no : -1 },
   
    { i: 'E1', x: 3, y: 1, w: 1, h: 5, emptyArea: true, unchange: true },
    { i: 'E2', x: 4, y: 1, w: 11, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true, },
    { i: 'E3', x: 16, y: 1, w: 6, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E4', x: 4, y: 4, w: 11, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E5', x: 15, y: 1, w: 1, h: 6, emptyArea: true, unchange: true },
    { i: 'E6', x: 16, y: 4, w: 6, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E7', x: 4, y: 7, w: 18, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E8', x: 0.5, y: 10, w: 3.5, h: 21, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E9 Sofa', x: 4, y: 9, w: 6, h: 12, emptyArea: true, unchange: true },
    { i: 'E10', x: 9, y: 15, w: 1, h: 6, emptyArea: true, unchange: true },
    { i: 'E11', x: 4, y: 17, w: 5, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
    { i: 'E12', x: 4, y: 19, w: 5, h: 1, cls: '', unOccupied: false, emptyArea: true, unchange: true },
   
   
    { i: 's1', x: 4, y: 0, w: 1, h: 1, cls: '', unOccupied: false, extension_no : -1 },
    { i: 's2', x: 5, y: 0, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's3', x: 6, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1},
    { i: 's4', x: 7, y: 0, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's5', x: 8, y: 0, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's6', x: 9, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's7', x: 10, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's8', x: 11, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's9', x: 12, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's10', x: 13, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's11', x: 14, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's12', x: 15, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's13', x: 16, y: 0, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's14', x: 17, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's15', x: 18, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's16', x: 19, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's17', x: 20, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's18', x: 21, y: 0, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    // { i: 's19', x: 22, y: 0, w: 1, h: 1, cls: '', unOccupied: false },
   
    { i: 's19', x: 4, y: 2, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's20', x: 5, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1},
    { i: 's21', x: 6, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's22', x: 7, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's23', x: 8, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's24', x: 9, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's25', x: 10, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's26', x: 11, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1},
    { i: 's27', x: 12, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's28', x: 13, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's29', x: 14, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    // { i: 's30', x: 15, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : 6 },
    { i: 's30', x: 16, y: 2, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1},
    { i: 's31', x: 17, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's32', x: 18, y: 2, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1},
    { i: 's33', x: 19, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's34', x: 20, y: 2, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's35', x: 21, y: 2, w: 1, h: 1, cls: '', unOccupied: false },
   
    { i: 's36', x: 4, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's37', x: 5, y: 3, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's38', x: 6, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's39', x: 7, y: 3, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's40', x: 8, y: 3, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's41', x: 9, y: 3, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's42', x: 10, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's43', x: 11, y: 3, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's44', x: 12, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's45', x: 13, y: 3, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's46', x: 14, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    // { i: 's49', x: 15, y: 3, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's47', x: 16, y: 3, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's48', x: 17, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's49', x: 18, y: 3, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's50', x: 19, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's51', x: 20, y: 3, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's52', x: 21, y: 3, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
   
   
    { i: 's53', x: 4, y: 5, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's54', x: 5, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's55', x: 6, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's56', x: 7, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's57', x: 8, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's58', x: 9, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's59', x: 10, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's60', x: 11, y: 5, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's61', x: 12, y: 5, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's62', x: 13, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's63', x: 14, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    // { i: 's67', x: 15, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's64', x: 16, y: 5, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's65', x: 17, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's66', x: 18, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's67', x: 19, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's68', x: 20, y: 5, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's69', x: 21, y: 5, w: 1, h: 1, cls: '', unOccupied: false  },
   
    { i: 's70', x: 4, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's71', x: 5, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's72', x: 6, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's73', x: 7, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's74', x: 8, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's75', x: 9, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's76', x: 10, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's77', x: 11, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's78', x: 12, y: 6, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's79', x: 13, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's80', x: 14, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    // { i: 's85', x: 15, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's81', x: 16, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's82', x: 17, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1},
    { i: 's83', x: 18, y: 6, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's84', x: 19, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1},
    { i: 's85', x: 20, y: 6, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
   
    { i: 's86', x: 8, y: 8, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's87', x: 9, y: 8, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's88', x: 10, y: 8, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's89', x: 11, y: 8, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's90', x: 12, y: 8, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's91', x: 13, y: 8, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's92', x: 14, y: 8, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's93', x: 15, y: 8, w: 1, h: 1, cls: '', unOccupied: false ,extension_no : -1 },
    { i: 's94', x: 16, y: 8, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's95', x: 17, y: 8, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's96', x: 18, y: 8, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's97', x: 19, y: 8, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 'SR-2', x: 20, y: 8, w: 1, h: 1, cls: '', unOccupied: false, emptyArea: true,unchange: true },
   
   
   
    { i: 's98', x: 0, y: 10, w: 0.5, h: 2, cls: '', unOccupied: false },
    { i: 's99', x: 0, y: 11, w: 0.5, h: 2, cls: '', unOccupied: false  },
    { i: 's100', x: 0, y: 12, w: 0.5, h: 2, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's101', x: 0, y: 13, w: 0.5, h: 2, cls: '', unOccupied: false },
    { i: 's102', x: 0, y: 14, w: 0.5, h: 2, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's103', x: 0, y: 15, w: 0.5, h: 2, cls: '', unOccupied: false  },
    { i: 's104', x: 0, y: 16, w: 0.5, h: 2, cls: '', unOccupied: false  },
   
    { i: 's105', x: 0, y: 19, w: 0.5, h: 2, cls: '', unOccupied: false  },
    { i: 's106', x: 0, y: 20, w: 0.5, h: 2, cls: '', unOccupied: false,extension_no : -1},
   
   
   
   
    { i: 's107', x: 4, y: 15, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's108', x: 5, y: 15, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's109', x: 6, y: 15, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's110', x: 7, y: 15, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's111', x: 8, y: 15, w: 1, h: 1, cls: '', unOccupied: false  },
   
    { i: 's112', x: 4, y: 16, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's113', x: 5, y: 16, w: 1, h: 1, cls: '', unOccupied: false  },
    { i: 's114', x: 6, y: 16, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
    { i: 's115', x: 7, y: 16, w: 1, h: 1, cls: '', unOccupied: false},
    { i: 's116', x: 8, y: 16, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1  },
   
    { i: 's117', x: 4, y: 17, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's118', x: 5, y: 17, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's119', x: 6, y: 17, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's120', x: 7, y: 17, w: 1, h: 1, cls: '', unOccupied: false, extension_no : -1 },
    { i: 's121', x: 8, y: 17, w: 1, h: 1, cls: '', unOccupied: false},
   
    { i: 's122', x: 10, y: 17, w: 0.5, h: 2, cls: '', unOccupied: false },
    { i: 's123', x: 10, y: 18, w: 0.5, h: 2, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's124', x: 10, y: 19, w: 0.5, h: 3, cls: '', unOccupied: false },
   
    { i: 's125', x: 4, y: 18, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's126', x: 5, y: 18, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's127', x: 6, y: 18, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's128', x: 7, y: 18, w: 1, h: 1, cls: '', unOccupied: false },
    { i: 's129', x: 8, y: 18, w: 1, h: 1, cls: '', unOccupied: false,extension_no : -1},
   
    { i: 's130', x: 1   , y: 19, w: 1.3, h: 1, cls: '', unOccupied: false },
    { i: 's131', x: 2.4, y: 19, w: 1.3, h: 1, cls: '', unOccupied: false },
    { i: 's132', x: 3.7, y: 19, w: 1.3, h: 1, cls: '', unOccupied: false,extension_no : -1},
    { i: 's133', x: 5, y: 19, w: 1.3, h: 1, cls: '', unOccupied: false, },
    { i: 's134', x: 6.3, y: 19, w: 1.3, h: 1, cls: '', unOccupied: false,  },
    { i: 's135', x: 7.6, y: 19, w: 1.3, h: 1, cls: '', unOccupied: false,extension_no : -1 },
    { i: 's136', x: 8.9, y: 19, w: 1.1, h: 1, cls: '', unOccupied: false },
    // { i: 's141', x: 8, y: 19, w: 1, h: 1, cls: '', unOccupied: false,extension_no : 27 },
    ],
   };
